# Open5GS SMF freeDiameter configuration

Identity = smf.localdomain;
Realm = localdomain;

ListenOn = "0.0.0.0";

LoadExtension = "dbg_msg_dumps.fdx";
LoadExtension = "rt_redirect.fdx";
LoadExtension = "dict_rfc5777.fdx";

ConnectPeer = "pcrf.localdomain" {
    No_TCP;
    No_SCTP;
    Port = 3868;
    Realm = localdomain;
};
