apiVersion: v1
data:
  smf.yaml: |
    logger:
      level: info
    smf:
      sbi:
        server:
          - address: 0.0.0.0
            port: 7777
        client:
          nrf:
            - uri: http://open5gs-nrf:7777
      pfcp:
        server:
          - address: 0.0.0.0
        client:
          upf:
            - address: open5gs-upf
      gtpc:
        server:
          - address: 0.0.0.0
      gtpu:
        server:
          - address: 0.0.0.0
      session:
        - subnet: 10.45.0.0/16
          gateway: 10.45.0.1
      dns:
        - 8.8.8.8
        - 8.8.4.4
      mtu: 1400
      freeDiameter: /etc/open5gs/freeDiameter/smf.conf
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"smf.yaml":"logger:\n  level: info\nsmf:\n  sbi:\n    server:\n      - address: 0.0.0.0\n        port: 7777\n    client:\n      nrf:\n        - uri: http://open5gs-nrf:7777\n  pfcp:\n    server:\n      - address: 0.0.0.0\n    client:\n      upf:\n        - address: open5gs-upf\n  gtpc:\n    server:\n      - address: 0.0.0.0\n  gtpu:\n    server:\n      - address: 0.0.0.0\n  session:\n    - subnet: 10.45.0.0/16\n      gateway: 10.45.0.1\n  dns:\n    - 8.8.8.8\n    - 8.8.4.4\n  mtu: 1400\n  freeDiameter: /etc/open5gs/freeDiameter/smf.conf\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"smf-config","namespace":"open5gs"}}
  creationTimestamp: "2026-07-31T09:09:08Z"
  name: smf-config
  namespace: open5gs
  resourceVersion: "25917"
  uid: 76db23c6-e9aa-410e-8bf1-42e5f4f81600
