apiVersion: v1
kind: ConfigMap
metadata:
  name: bsf-config
  namespace: open5gs
data:
  bsf.yaml: |
    logger:
      level: info
    bsf:
      sbi:
        server:
          - address: 0.0.0.0
            port: 7777
        client:
          nrf:
            - uri: http://open5gs-nrf:7777
