apiVersion: v1
kind: ConfigMap
metadata:
  name: udr-config
  namespace: open5gs
data:
  udr.yaml: |
    logger:
      level: info
    db_uri: mongodb://mongodb/open5gs
    udr:
      sbi:
        server:
          - address: 0.0.0.0
            port: 7777
        client:
          nrf:
            - uri: http://open5gs-nrf:7777
