apiVersion: v1
kind: Service
metadata: { name: open5gs-webui, namespace: open5gs }
spec:
  type: NodePort
  selector: { app: open5gs-webui }
  ports:
    - port: 9999
      targetPort: 9999
      nodePort: 30999
